const testingData = [
  {
    id: '1',
    topic: '香港邊度揾到村上春樹嘅小說？',
    creator: '將軍澳姜濤',
    lastUpdate: '2021/05/30 13:45',
    gender: 'male',
    pageCount: 10,
    totalComment: 150,
    likeCount: 2,
  },
  {
    id: '2',
    topic: '有咩愛情小說好睇？',
    creator: '鳴人',
    lastUpdate: '2021/05/30 13:45',
    gender: 'unknown',
    pageCount: 10,
    totalComment: 10,
    likeCount: 5,
  },
  {
    id: '3',
    topic: '你地最鐘意古龍邊部作品？',
    creator: '將軍澳姜濤',
    lastUpdate: '2021/05/30 13:45',
    gender: 'male',
    pageCount: 10,
    totalComment: 9,
    likeCount: 9,
  },
  {
    id: '4',
    topic: '有冇人睇開金庸小說？',
    creator: '晴晴',
    gender: 'male',
    lastUpdate: '2021/05/30 13:45',
    pageCount: 10,
    totalComment: 150,
    likeCount: 20,
  },
  {
    id: '5',
    topic: '知唔知邊度買小說最齊？',
    creator: '將軍澳姜濤',
    gender: 'male',
    lastUpdate: '2021/05/30 13:45',
    pageCount: 10,
    totalComment: 9,
    likeCount: 9,
  },
  {
    id: '6',
    topic: '東野圭吾一定係日本推理小說最好睇',
    creator: '晴晴',
    lastUpdate: '2021/05/30 13:45',
    gender: 'female',
    pageCount: 10,
    totalComment: 150,
    likeCount: 20,
  },
  {
    id: '7',
    topic: '日本小說有冇推介？',
    creator: '晴晴',
    lastUpdate: '2021/05/30 13:45',
    gender: 'female',
    pageCount: 10,
    totalComment: 150,
    likeCount: 20,
  },
];

export default testingData;
